steps:
  - name: "gcr.io/cloud-builders/npm:node-16.18.0"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm:node-16.18.0"
    args: ["run", "build"]
  - name: 'gcr.io/immoxperts/firebase'
    args:
      - deploy
      - --only=hosting

options:

logsBucket: 'gs://immoxperts-devops'
timeout: '1600s'


  
